### ISSUE TITLE
error al logearse a la aplicación

### ISSUE THREAD

**Issue by DanielBrownM** [pingeso2016/SCJ#1]
al tratar de logearme a la aplicación surge el siguiente error:
serverError: class javax.el.PropertyNotFoundException Target Unreachable, identifier 'managedBeanLogin' resolved to null

**Comment by gigoox** [comment]
Si no tienes las relaciones en la bd, al buscar por el usuario, y obtener su rol, te va retornar un objeto Null. Por eso es el error.

**Comment by DanielBrownM** [comment]
Ahí me funcionó. Gracias.
