### ISSUE TITLE
problema mangedbeans en netbeans

### ISSUE THREAD

**Issue by DanielBrownM** [pingeso2016/SCJ#11]
problema en todas las ramas, proyecto recién clonado en todos los managedbeans.

el problema está en que netbeans detecta como error las líneas de la imagen en el link al final del post pero el programa funciona correctamente :s

http://puu.sh/p6pwn/902a0ad398.png

**Comment by gigoox** [comment]
Para solucionar el problema se debe borra la carpeta index en la carpeta cache de netbeans

**Comment by DanielBrownM** [comment]
donde está la carpeta de cache en win10?

**Comment by DanielBrownM** [comment]
C:\Users\<user>\AppData\Local\NetBeans\Cache

**Comment by DanielBrownM** [comment]
probado funcionando 10/10
